//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class quanlydogoEntities : DbContext
    {
        public quanlydogoEntities()
            : base("name=quanlydogoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<login> logins { get; set; }
        public virtual DbSet<orderCu> orderCus { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<product_order> product_order { get; set; }
        public virtual DbSet<stock> stocks { get; set; }
        public virtual DbSet<stock_product> stock_product { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
