//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stock_product
    {
        public int id { get; set; }
        public Nullable<int> stockId { get; set; }
        public Nullable<int> productID { get; set; }
        public int quantity { get; set; }
        public Nullable<int> orderProduct { get; set; }
        public string timeStamp { get; set; }
    
        public virtual product product { get; set; }
        public virtual stock stock { get; set; }
    }
}
